//------------------------------------------------------------------------------
//	File:					cube.h
//	Date:					11/02/94
//	Author:				Bretton Wade
//
//	Description:	this file contains the function for cube generation
//
//------------------------------------------------------------------------------

#include	"matrix_3d.h"
#include	"listptr_3d.h"

#ifndef	CUBE
#define	CUBE

//------------------------------------------------------------------------------
//	functions
//------------------------------------------------------------------------------
listptr	Cube (matrix_3d transformation);																						//	compute a cube given a transformation

//------------------------------------------------------------------------------

#endif	//CUBE
