//------------------------------------------------------------------------------
//	File:					pi.cpp
//	Date:					9/30/96
//	Author:				Bretton Wade
//
//	Description:	this file contains the definitions of PI and accessories
//
//------------------------------------------------------------------------------

#ifndef	DEFINE_PI
#define	DEFINE_PI

//------------------------------------------------------------------------------
void	DefinePI (void);																													//	fill in the definitions of PI

//------------------------------------------------------------------------------
extern	real	PI;																																//	3.14
extern	real	OVER_PI;																													//	3.14
extern	real	TWO_PI;																														//	6.28
extern	real	OVER_TWO_PI;																											//	0.16
extern	real	PI_OVER_TWO;																											//	1.57

//------------------------------------------------------------------------------

#endif	//	DEFINE_PI
